# Elasticsearch Configuration for Agentic RAG System

cluster.name: "agentic-rag-cluster"
node.name: "agentic-rag-node-1"

# Network settings
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery settings
discovery.type: single-node

# Security settings (disabled for development)
xpack.security.enabled: false
xpack.security.enrollment.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# Monitoring settings
xpack.monitoring.collection.enabled: true

# Index settings
action.auto_create_index: true
action.destructive_requires_name: true

# Memory settings
bootstrap.memory_lock: true

# Logging
logger.level: INFO

# Index lifecycle management
xpack.ilm.enabled: true

# Index templates for agentic-rag logs
index.number_of_shards: 1
index.number_of_replicas: 0
index.refresh_interval: 5s

# Cluster settings
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 85%
cluster.routing.allocation.disk.watermark.high: 90%
cluster.routing.allocation.disk.watermark.flood_stage: 95%
